# Uncomment the next line to define a global platform for your project
platform :ios, '16.2'
project 'FSPlayerExample.xcodeproj'

use_frameworks!

target 'FSPlayerExample' do
  # Compile the local Sources/FSPlayer implementation while developing the framework.
  pod 'FSPlayer/Debug', :path => '../'
  pod 'LottieXCFramework', :podspec => '../Vendor/LottieXCFramework.podspec'
end

target 'FSPlayerExampleTests' do
  inherit! :search_paths
  pod 'FSPlayer/Debug', :path => '../'
end

target 'FSPlayerExampleUITests' do
  inherit! :search_paths
end
